version: '3.7'
services:
  postgres:
    image: 'postgres:16'
    volumes:
      - ./.docker/pg-init-scripts:/docker-entrypoint-initdb.d
    ports:
      - '32100:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_MULTIPLE_DATABASES: default,account-service,product-service
  rabbitmq:
    image: 'rabbitmq:3-management'
    ports:
      - '32200:5672'
      - '32210:15672'
