name: GitHub Actions CI

on: push

jobs:
  build:
    strategy:
      matrix:
        java: [17, 21]
      fail-fast: false
    name: Java ${{ matrix.java }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Java ${{ matrix.java }}
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java }}
      - name: Build with Maven
        run: ./mvnw install -V
